sonar.projectKey=User-Standart_API-5SEM-FRONTEND
sonar.projectName=API-5SEM-FRONTEND
sonar.projectVersion=1.0
sonar.organization=user-standart
sonar.sources=app
sonar.exclusions=node_modules/**,.nuxt/**,.output/**,coverage/**,dist/**,**/*.spec.ts,**/*.test.ts
sonar.tests=app/tests
sonar.test.inclusions=**/*.spec.ts,**/*.test.ts
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
sonar.typescript.tsconfigPath=tsconfig.json
